version: '3.8'

services:
  # Game Server (Rust)
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEBSOCKET_PORT:-5000}:${WEBSOCKET_PORT:-5000}"
    networks:
      - mmo-network
    restart: unless-stopped
    env_file:
      - .env.server
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST:-0.0.0.0}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT:-5000}
      - WORLD_BOUNDS_X=${WORLD_BOUNDS_X:-1000.0}
      - WORLD_BOUNDS_Y=${WORLD_BOUNDS_Y:-1000.0}
      - PLAYER_SPEED=${PLAYER_SPEED:-100.0}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEBSOCKET_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Client (TypeScript/Vite)
  # client:
  #   build:
  #     context: ./client-test-tool
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - mmo-network
  #   depends_on:
  #     - game-server
  #   restart: unless-stopped
  #   env_file:
  #     - ./client-test-tool/.env.client
  #   environment:
  #     - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL:-ws://localhost:5000}
  #   volumes:
  #     - ./client-test-tool:/app
  #     - /app/node_modules

networks:
  mmo-network:
    driver: bridge